#!/bin/zsh

##### colors #####
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

##### git #####
alias ga='git add'
alias gap='git add --patch'
alias gb='git branch'
alias gba='git branch -a'
alias gc='git commit -v'
alias gca='git commit -va'
alias gco='git checkout'
alias gd='git diff'
alias gl='git pull'
# pretty logs
alias glo="git log --graph --pretty=format:'%Cred%h%Creset %an: %s - %Creset %C(yellow)%d%Creset %Cgreen(%cr)%Creset' --abbrev-commit --date=relative"
alias gp='git push'
# show git-status in short mode, with branch info
alias gst='git status -sb'
# git-extras
alias gpc='git cush'
alias nvm='git nvm'
alias gt='git track'
# thanks holman, this rules
alias grm="git status | grep deleted | awk '{print \$3}' | xargs git rm"

##### save some typing.. #####
alias s='sudo'
alias c='cd'
alias g='apt-get'
alias rmr='rm -r'
alias ge='gedit'
alias tgz='tar -zcvf'
alias untgz='tar -zxvf'
alias tbz='tar -jczf'
alias untbz='tar -jxvf'
alias iwcfg='iwconfig'
alias ifcfg='ifconfig'

##### ls (need to define differently for OSX) #####
if [ -e "/Users" ]; then
	alias l='ls -G'
	alias la='ls -Ga'
	alias ll='ls -lh'
else
	alias l='ls --color'
	alias la='ls --color -a'
	alias ll='ls --color -lh'
fi

##### editors #####
alias e='emacs'
alias v='vim'

##### coding #####
alias rb='ruby'
alias pl='perl'
alias py='python'
