#!/bin/zsh

##### colors #####
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

##### git #####
alias ga='git add'
alias gap='git add --patch'
alias gb='git branch'
alias gba='git branch -a'
alias gc='git commit -v'
alias gca='git commit -va'
alias gco='git checkout'
alias gd='git diff'
alias gl='git pull'
# pretty logs
alias glo="git log --graph --pretty=format:'%Cred%h%Creset %an: %s - %Creset %C(yellow)%d%Creset %Cgreen(%cr)%Creset' --abbrev-commit --date=relative"
alias gp='git push'
# show git-status in short mode, with branch info
alias gst='git status -sb'
# thanks holman, this rules
alias grm="git status | grep deleted | awk '{print \$3}' | xargs git rm"
# clean + update all git submodules
alias gus="git submodule foreach 'git reset --hard HEAD; git checkout master; git pull origin master'"

##### save some typing.. #####
alias s='sudo'
alias c='cd'
alias ..='cd ../'
alias ...='cd ../../'
alias ....='cd ../../../'
alias pu='pushd'
alias po='popd'
alias g='apt-get'
alias rmr='rm -r'
alias mkd='mkdir -p'
alias ge='gedit'
alias tgz='tar -zcvf'
alias untgz='tar -zxvf'
alias tbz='tar -jczf'
alias untbz='tar -jxvf'
alias iwcfg='iwconfig'
alias ifcfg='ifconfig'

#### convert to decimal ####
alias 2d='printf "%d\n" '

#### more typing saved with global aliases ####
alias -g .lc="| wc -l"	    # line count
alias -g .dn="2>&1 > /dev/null"
alias -g .h="| head"
alias -g .t="| tail"
alias -g .tf="| tail -f"
alias -g .l="| less"
alias -g .m="| md5sum"	    # MD5 sum
alias -g .s="| shasum"	    # SHA1 sum
alias -g .c="| pbcopy"
alias -g .strip="| sed 's/^[ \t]\+//; s/[ \t]\+$//'"

##### ls (need to define differently for OSX) #####
if [ -e "/Users" ]; then
	alias l='ls -GlAh'
	alias la='ls -GA'
	alias ll='ls -lh'
else
	alias l='ls --color -lAh'
	alias la='ls --color -A'
	alias ll='ls --color -lh'
fi

##### editors #####
alias e='emacsclient'
alias v='vim'

##### coding #####
alias rb='ruby'
alias pl='perl'
alias py='python'
alias no='node'
alias ra='racket -il readline'

##### sniff HTTP traffic #####
alias sniff="sudo ngrep -d 'en1' -t '^(GET|POST) ' 'tcp and port 80'"

##### HTTP server ######
alias http="python3 -m http.server || python2 -m SimpleHTTPServer"

##### name iTerm tab #####
alias nt='nametab'

##### format JSON! #####
alias pj='python -mjson.tool'

##### appengine #####
alias gaea='appcfg.py --oauth2'
alias gaed='dev_appserver.py .'
alias gaer='remote_api_shell.py'
alias gaeu='appcfg.py --oauth2 update .'
alias gaeua='appcfg.py --oauth2 -V dev update . && appcfg.py --oauth2 update . -V'

##### stanford #####
alias myth='ssh myth.stanford.edu'
alias corn='ssh corn.stanford.edu'
alias jamie='ssh jamie.stanford.edu'
alias farmshare="cd /farmshare/user_data/$USER"
alias myq="qstat -nu $USER"

#### stanford nlp ####
if [ -e "/afs/cs.stanford.edu" ]; then
    alias qsub="qsub -q nlp"
fi

source ~/.zsh/local_aliases
